### ISSUE TITLE
Caused by: java.util.MissingResourceException: Can't find bundle for base name javax.servlet.LocalStrings, locale zh_CN

### ISSUE THREAD

**Issue by liweinan** [resteasy/resteasy-examples#76]
@jamezp When I'm running `bootable-jar` example in my local environment, I got this problem:

![image](https://user-images.githubusercontent.com/201907/141901561-ec62494a-cb3c-4cea-99b4-ebde07c8cdad.png)

I tried to set locale in `pom.xml` but seems can't fix the problem. Could you please help to give some suggestions to set locale properly? Thanks!

**Comment by jamezp** [comment]
@liweinan If you add the following to the POM it will fix it. 
```xml
<dependency>
    <groupId>jakarta.servlet</groupId>
    <artifactId>jakarta.servlet-api</artifactId>
    <version>4.0.4</version>
    <scope>test</scope>
</dependency>
```

However, I really think we need to clean up a bunch of the dependencies. We're using a mix of Java EE and Jakarta dependencies.
