### ISSUE TITLE
Add an MicroProfile OpenAPI example

### ISSUE THREAD

**Issue by jamezp** [resteasy/resteasy-examples#95]
The `jaxrs-swagger-example`, `resteasy-wadl-wildfly` and `wadl-example` will be removed in #94. We should, however, introduce a new example which uses OpenAPI. This would show accomplishing the same thing.

**Comment by liweinan** [comment]
I'll take this.

**Comment by jamezp** [comment]
Please note we likely need to add a resteasy-microprofile-examples before this can be done.

**Comment by liweinan** [comment]
@jamezp Thanks for telling! I'll check microprofile firstly and then work on this.
